-- VectorCAST 18.sp5 (03/03/19)
-- Test Case Script
-- 
-- Environment    : ENV_MONITORED_ADA
-- Unit(s) Under Test: UNIT
-- 
-- Script Features
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:ADA_DIRECT_ARRAY_INDEXING
--

-- Unit: UNIT

-- Subprogram: ISPOSITIVE

-- Test Case: ISPOSITIVE
TEST.UNIT:UNIT
TEST.SUBPROGRAM:ISPOSITIVE
TEST.NEW
TEST.NAME:ISPOSITIVE
TEST.VALUE:UNIT.ISPOSITIVE.X:2
TEST.EXPECTED:UNIT.ISPOSITIVE.return:TRUE
TEST.END
